### ISSUE TITLE
demo打开,好像很多页面都切换不了呢?

### ISSUE THREAD

**Issue by ShawshankLin** [beautifulBoys/XiaoMi-Shop#1]

**Comment by beautifulBoys** [comment]
这会只有 4 个页面，首页，详情页，购物车页，搜索页面，欢迎页面算半个。其他的就是做了个效果，并没有具体写太多页面（例如最下方的导航这个就是做了个效果，并不能切换。），因为工作比较忙，并且都是重复功能，所以就没有补充这些个页面。

其他没有写的非常简单码代码的页面像下面这些都没有写：

主要的功能就是：数据绑定（循环，值绑定，事件绑定等），路由导航（首页 -> 详情页），还有动画处理（欢迎页），复杂交互处理（购物车），这些可以研究下，希望对你有帮助。
