### ISSUE TITLE
请问有没有您个人网站的分享

### ISSUE THREAD

**Issue by kun910202** [beautifulBoys/XiaoMi-Shop#3]
请问有没有您个人网站的分享 谢谢

**Comment by beautifulBoys** [comment]
个人网站有一个，目前只整理了少部分 2015年-2017年 个人项目（18年的项目到年末整理出来，也算是积累吧。）
个人网站：https://beautifulboys.github.io/
备用：http://47.95.212.47:8888/（域名忘记续费过期了，汗）

具体情况请到网站查看，如有疑问欢迎提问及发邮件。
以上，感谢关注，共同进步。

**Comment by kun910202** [comment]
谢谢楼主的分享，https://beautifulboys.github.io/您的网站源码开源吗，想学习下这种类型的网站。谢谢

**Comment by beautifulBoys** [comment]
所有的项目学习交流，请随意使用。但是请别商用（里面的图片，设计，思路 部分来源网络，无授权）。
所有项目在我的仓库里面都可以找到源码。
https://github.com/beautifulBoys 里面寻找源码。
如果找不到的，可以截图加你想做要什么项目的源码，发邮箱：1298947916@qq.com，看到必回。

**Comment by kun910202** [comment]
感谢楼主的分享，已follow

**Comment by beautifulBoys** [comment]
1298947916@qq.com
 
发件人： kun910202
发送时间： 2018-06-22 15:43
收件人： beautifulBoys/vue-XiaoMi-Shop
抄送： Jason_lixin; Comment
主题： Re: [beautifulBoys/vue-XiaoMi-Shop] 请问有没有您个人网站的分享 (#3)
感谢楼主的分享，已follow
